contact creation with controller
WildCodeSchool/orleans-202103-php-project-treebz pull request #100
Opened 2021-06-12 14:11 UTC by ChristianOlmedo

2021-06-14 08:00 UTC, Vannou28 approved these changes

2021-06-14 09:01 UTC, sblondeau requested changes

2021-06-14 09:01 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $entityManager->persist($contact);
pas de persist / flush mais l'envoi du mail
penser à créer un layoutEmail

2021-06-16 14:57 UTC, Vannou28 approved these changes

2021-06-16 15:09 UTC, sblondeau requested changes

2021-06-16 19:01 UTC, ChristianOlmedo commented on src/Entity/Contact.php
> +     * @Assert\NotBlank(message="Ce champ est requis")
Si tu parles des messages d'erreur, ça ne fonctionne pas j'ai essayé =(

2021-06-17 07:16 UTC, ChristianOlmedo commented on src/Entity/Contact.php
> +     * @Assert\NotBlank(message="Ce champ est requis")
Ah c'est bon en fait, je pense avoir compris

2021-06-17 07:44 UTC, Vannou28 approved these changes

2021-06-17 08:53 UTC, sblondeau approved these changes

2021-06-17 08:54 UTC, merged