Us7_01 step2 create member
WildCodeSchool/orleans-202103-php-project-treebz pull request #101
Opened 2021-06-14 20:46 UTC by Vannou28

2021-06-15 07:22 UTC, gerseystelmach approved these changes

2021-06-15 09:43 UTC, sblondeau requested changes

2021-06-15 09:43 UTC, sblondeau commented on migrations/Version20210610205201.php
>          $this->addSql('CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(500) NOT NULL, color_text VARCHAR(7) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
attention, tu créé la table theme ici alors que ce n'est pas ton US.
Cette création est déjà gérée dans une autre migration. Attention à bien regardé ce qui est généré quand tu fais des migrations, et pense à systématiquement faire un doctrine:migration:migrate quand tu pull DEV et donc avant de créer ta propre migration

2021-06-15 19:52 UTC, gerseystelmach submitted a review, later dismissed

2021-06-16 09:23 UTC, sblondeau requested changes

2021-06-16 09:23 UTC, sblondeau commented on src/Entity/Member.php
> +     */
manque Assert\Length max 255

2021-06-16 09:23 UTC, sblondeau commented on src/Entity/Member.php
> +    * @var File
manque des assert sur la gestion de fichies (types mimes accetpés et maxSize du fichier uploadés). La doc est là https://symfony.com/doc/current/reference/constraints/File.html

2021-06-16 12:55 UTC, Vannou28 commented on src/Entity/Member.php
> +    * @var File
ok merci

2021-06-17 07:05 UTC, Valentin-int submitted a review, later dismissed

2021-06-17 07:42 UTC, gerseystelmach submitted a review, later dismissed

2021-06-17 08:57 UTC, sblondeau requested changes

2021-06-17 08:57 UTC, sblondeau commented on src/Entity/Member.php
> +     * maxSize="5242880",
memes remarques que pour Valentin sur sa PR (tu peux voir avec lui si besoin)
- 2M max pas 5M (2M est la limite par défaut configuré dans PHP)
- les images, png, jpg et webp me semble suffisant. Gif et pdf pas pertinent je pense

2021-06-17 08:57 UTC, sblondeau commented on src/Form/MemberType.php
> +                    new File([
constraints inutile car déjà gérée dans l'@Assert

2021-06-17 09:42 UTC, ChristianOlmedo approved these changes

2021-06-17 11:36 UTC, sblondeau approved these changes

2021-06-17 13:27 UTC, gerseystelmach approved these changes

2021-06-17 14:45 UTC, sblondeau approved these changes

2021-06-17 14:45 UTC, merged