Init project Treeb'z
WildCodeSchool/orleans-202103-php-project-treebz pull request #12
Opened 2021-05-28 14:39 UTC by Valentin-int

2021-05-28 14:40 UTC, gerseystelmach approved these changes

2021-05-28 14:41 UTC, gerseystelmach approved these changes

2021-05-28 14:45 UTC, gerseystelmach submitted a review, later dismissed

2021-05-28 14:48 UTC, Vannou28 approved these changes

2021-05-28 15:01 UTC, sblondeau requested changes

2021-05-28 15:01 UTC, sblondeau commented on templates/layout_admin.html.twig
> +{% block title %} - {{ parent() }}{% endblock %}
ajoute un "Admin" peut etre dans le title justement pour différencier

2021-05-28 15:01 UTC, sblondeau commented on assets/styles/variables.scss
> +$indigo: #6610f2;
vous n'avez sans doute pas besoin de définir toutes ces couleurs dès à présent? 
de plus je n'aime pas trop donner des noms de couleurs aux variables, plutot justement rester sur des concepts "primary, secondary" que "blue ou yellow" car si tu décides de changer un jour de couleur primaire, tu risques de fnir avec une varialbe $blue qui contient du rose... ;-)

2021-05-31 08:15 UTC, Vannou28 approved these changes
bon boulot val!!!

2021-05-31 08:23 UTC, sblondeau approved these changes

2021-05-31 08:23 UTC, merged