list and preview of members and MemberFixctures
WildCodeSchool/orleans-202103-php-project-treebz pull request #122
Opened 2021-06-17 20:21 UTC by Vannou28

2021-06-17 20:43 UTC, ChristianOlmedo submitted a review, later dismissed

2021-06-18 07:13 UTC, sblondeau requested changes

2021-06-18 07:13 UTC, sblondeau commented on src/DataFixtures/MemberFixtures.php
> +        $member-> setPicture('portrait.jpg');
pour les images, tu essaies de faire des fixutres sur qq chose qui est uploadé et donc au final dans /public/uploads et non dans assets/images
donc tu ne dois pas mettre d'image dans /assets/images pour ça. C'est un peu plus compliqué, mais tu peux utiliser Facker et la méthode image, pour lui faire télécharger une image (un placeholder) dans le dossier de ton choix avec le nom de ton choix, ce qui résoud le pb. https://fakerphp.github.io/formatters/image/#image_1

2021-06-18 07:13 UTC, sblondeau commented on src/DataFixtures/MemberFixtures.php
> +        sleep(1);
pourquoi le sleep ?

2021-06-18 07:13 UTC, sblondeau commented on templates/member/index.html.twig
> +                                <div class="card m-2" style="width: 20rem;">
attention aux copier/coller de la doc de bootstrape
1. pas de style en inline
2. pas de h5 si la hierarchie des titres n'est pas respectée

2021-06-18 07:13 UTC, sblondeau commented on templates/member/index.html.twig
> +                                <h3> colspan="5">Pas encore de membre enregistré </h3>
pb avec ton attribut colspan là qui je pense n'a rien à faire ici et est en dehors de la balise

2021-06-18 07:17 UTC, gerseystelmach approved these changes

2021-06-18 07:20 UTC, Vannou28 commented on src/DataFixtures/MemberFixtures.php
> +        sleep(1);
le sleep c'est juste pour avoir une petite diffrence dans la database pour le setUpdateAt

2021-06-22 10:06 UTC, Valentin-int approved these changes

2021-06-22 12:35 UTC, sblondeau requested changes

2021-06-22 12:35 UTC, sblondeau commented on config/packages/vich_uploader.yaml
> +                inject_on_load: false
ce sont les valeurs par défaut, pas la peine de le mettre
par contre il te manque le namer

2021-06-22 12:38 UTC, closed without merging