US17 - Fixtures for Theme and Command
WildCodeSchool/orleans-202103-php-project-treebz pull request #137
Opened 2021-06-22 16:05 UTC by gerseystelmach

2021-06-22 16:11 UTC, gerseystelmach commented
pu

2021-06-23 06:16 UTC, ChristianOlmedo approved these changes

2021-06-23 07:08 UTC, sblondeau requested changes

2021-06-23 07:08 UTC, sblondeau commented on src/Controller/UserController.php
> +        return $this->render('user/index.html.twig', [
que veux tu faire dans cette US ? juste faire des fixtures ne correspond pas à une fonctionnalité, ça doit etre un tache d'une US. 
Ou s'il y a des fixtures manquantes sur une US déjà faites, ça doit être juste un fix. Là c'est ni l'un ni l'autre ;-)

2021-06-23 11:28 UTC, ChristianOlmedo approved these changes

2021-06-23 12:01 UTC, sblondeau approved these changes

2021-06-23 12:01 UTC, merged