Fix_Design_Game Creation and Buttons
WildCodeSchool/orleans-202103-php-project-treebz pull request #142
Opened 2021-06-23 13:32 UTC by gerseystelmach

2021-06-23 16:56 UTC, Vannou28 submitted a review, later dismissed

2021-06-24 06:25 UTC, sblondeau requested changes
attention, les images uploadées ne doivent pas etre versionnées.
Il faut que tu mettes le contenu du dossier uploads dans le .gitignore et que tu enlèves ces 2 images (suppression ou git rm)

2021-06-24 09:26 UTC, ChristianOlmedo approved these changes

2021-06-24 11:39 UTC, sblondeau approved these changes

2021-06-24 11:39 UTC, merged