Fix in the path for Theme image exhibit
WildCodeSchool/orleans-202103-php-project-treebz pull request #143
Opened 2021-06-23 14:10 UTC by gerseystelmach

2021-06-23 16:58 UTC, Vannou28 approved these changes

2021-06-24 06:28 UTC, sblondeau requested changes
meme remarque que la PR précédente, tu as des images d'uploads versionnées, il ne faut pas

2021-06-24 06:28 UTC, sblondeau commented on templates/gameCreation/theme.html.twig
> +                                <img src="/uploads/{{ entity.image }}" alt="Treebz Card">
tu as mis Vich pour les themes ? 
donc il fuat mettre plutot <img src="{{ vich_uploader_asset(theme_mapping) }}" alt="{{ entity.image }}">
ou sinon au moins un {{ asset('/uploads/' ~ {{ entity.image }} ) }}

2021-06-24 09:27 UTC, ChristianOlmedo approved these changes

2021-06-24 11:39 UTC, sblondeau approved these changes

2021-06-24 14:30 UTC, Vannou28 approved these changes

2021-06-24 15:46 UTC, merged