S04 us16 mdp oublier
WildCodeSchool/orleans-202103-php-project-treebz pull request #158
Opened 2021-06-24 09:29 UTC by Valentin-int

2021-06-24 09:36 UTC, ChristianOlmedo approved these changes

2021-06-24 15:59 UTC, sblondeau requested changes

2021-06-24 15:59 UTC, sblondeau commented on migrations/Version20210624083810.php
> +        $this->addSql('DROP TABLE command_theme');
tu es sur du drop dans ta migration là ?

2021-06-24 15:59 UTC, sblondeau commented on src/Controller/security/ResetPasswordController.php
> +            $this->addFlash('secondary', 'Votre mot de passe à bien été réinitialiser');
réinitialisé

2021-06-24 15:59 UTC, sblondeau commented on src/Controller/security/ResetPasswordController.php
> +            ->subject('Your password reset request')
tu as mis en place le mail ? il faut traduire ça dans ce cas

2021-06-24 15:59 UTC, sblondeau commented on src/Controller/security/ResetPasswordController.php
> +            ->subject('Your password reset request')
et ne pas mettre l'adresse en dur car ça ne sera pas celle là à terme. Faut que ça soit configurable dans le .env

2021-06-24 15:59 UTC, sblondeau commented on templates/security/login.html.twig
> +                <a href="{{ path('app_forgot_password_request') }}">Mot de passe oublier ?</a>
oublié <= attention à l'ortho

2021-06-24 15:59 UTC, sblondeau commented on templates/security/reset_password/check_email.html.twig
> +        <p>Si vous ne recevez pas d'email, veuillez vérifier votre dossier spam ou <a href="{{ path('app_forgot_password_request') }}">Réessayer</a>.</p>
Si vous ne recevez pas d'email, veuillez vérifier vos messages indésirables ou <a href="{{ path('app_forgot_password_request') }}">réessayez</a>

2021-06-24 20:18 UTC, gerseystelmach approved these changes

2021-06-25 08:02 UTC, sblondeau requested changes

2021-06-25 08:02 UTC, sblondeau commented on src/Controller/security/ResetPasswordController.php
> +        $mailerFrom = $this->getParameter('mailer_from');
ok bien mieux, dernière chose, dans service.yaml, tu fais     mailer_from: '%env(resolve:MAILER_FROM_ADDRESS)%'
ce qui est très bien, mais ça oblige a crée MAILER_FROM_ADDRESS, or si j'installe le projet je ne le sais pas

il faut donc penser à mettre à jour .env  (celui qui est versionné) pour ajouter MAILER_FROM_ADDRESS (avec une valeur bidon d'exemple). (pareil pour MAILER_DSN ou autre). Ains quand je clone le projet, je sais directement que j'ai ça a configurer. Le .env est un fichier "modèle"

2021-07-01 12:50 UTC, gerseystelmach submitted a review, later dismissed

2021-07-01 13:00 UTC, sblondeau requested changes

2021-07-02 09:57 UTC, gerseystelmach approved these changes

2021-07-02 15:51 UTC, sblondeau approved these changes

2021-07-02 15:52 UTC, merged