S01US06-01
WildCodeSchool/orleans-202103-php-project-treebz pull request #17
Opened 2021-06-03 12:28 UTC by ChristianOlmedo

2021-06-03 12:55 UTC, Valentin-int approved these changes

2021-06-03 13:23 UTC, Valentin-int submitted a review, later dismissed

2021-06-03 15:00 UTC, gerseystelmach approved these changes

2021-06-03 15:01 UTC, gerseystelmach approved these changes

2021-06-03 16:11 UTC, Vannou28 approved these changes
it's good ;-)))

2021-06-03 17:10 UTC, sblondeau requested changes

2021-06-03 17:10 UTC, sblondeau commented on assets/styles/home/home.scss
> +    font-size: calc(#{$font-size} * 4);
en scss, tu peux faire direct $font-size * 4 sans utiliser calc()

2021-06-03 17:10 UTC, sblondeau commented on assets/styles/home/home.scss
> +@media screen and (max-width: 1000px) {
non pas de media queries pour ça.

pour les petits écrans, généralement meme si tu ne change pas la taille ça doit être ok. 
pour les margin, tu as des classes de bootstrap pour gérer en fonction des tailles d'écran

2021-06-03 17:10 UTC, sblondeau commented on templates/home/index.html.twig
> +		{{ parent() }}
indentation

2021-06-03 18:33 UTC, ChristianOlmedo commented on assets/styles/home/home.scss
> +    font-size: calc(#{$font-size} * 4);
Ok je l'ignorais, effectivement ça fonctionne

2021-06-03 18:33 UTC, ChristianOlmedo commented on templates/home/index.html.twig
> +		{{ parent() }}
Fait

2021-06-03 18:36 UTC, ChristianOlmedo commented on assets/styles/home/home.scss
> +@media screen and (max-width: 1000px) {
Ok pour les margin j'ai changé en bootstrap, par contre pour la taille de police, en version téléphone ça garde la taille initiale et c'est donc illisible.

2021-06-03 18:41 UTC, Valentin-int approved these changes

2021-06-04 07:08 UTC, Vannou28 approved these changes
it's good for me

2021-06-04 07:18 UTC, Valentin-int submitted a review, later dismissed

2021-06-04 07:44 UTC, sblondeau requested changes

2021-06-04 07:44 UTC, sblondeau commented on assets/styles/home/home.scss
> +@media screen and (max-width: 1000px) {
astuce pour rendre des typos fluides (donc pas besoin des media queries)
https://css-tricks.com/snippets/css/fluid-typography/

de plus si vraiment tu dois en faire, utilises les bons breakpoints (ceux de boostrap)

2021-06-04 07:45 UTC, Valentin-int submitted a review, later dismissed

2021-06-04 08:24 UTC, Valentin-int approved these changes

2021-06-04 08:25 UTC, gerseystelmach approved these changes

2021-06-04 08:29 UTC, sblondeau submitted a review, later dismissed

2021-06-04 08:35 UTC, Valentin-int approved these changes

2021-06-04 08:37 UTC, merged