Fix link command member theme link fixtures
WildCodeSchool/orleans-202103-php-project-treebz pull request #207
Opened 2021-07-01 15:31 UTC by Vannou28

2021-07-02 08:37 UTC, gerseystelmach approved these changes

2021-07-02 15:54 UTC, sblondeau requested changes

2021-07-02 15:54 UTC, sblondeau commented on src/DataFixtures/ThemeFixtures.php
> +    public const LINK_IMAGES = 'public/build/canva_png/';
ok ça me semble pas très logique comme approche, ton but c'est d'utiliser des images perso pour des fixtures ? dans ce cas, le mieux serait que tu creéé un dossier image dans le dossier data_fixtures et que tu ailles faire ton copy() depuis ce repertoire, plus logique que de les mettre dans les assets public

2021-07-05 09:38 UTC, gerseystelmach submitted a review, later dismissed

2021-07-05 10:12 UTC, sblondeau requested changes
il faut du coup retirer les images de canva qui sont dans assets

2021-07-05 10:12 UTC, sblondeau commented on src/DataFixtures/MemberFixtures.php
> +    public const MEMBERSNAME = ['GRAND-PERE', 'GRAND-MERE', 'PAPA', 'MAMAN', 'FILS', 'FILLE', 'CHIEN'];
MEMBER_NAMES

2021-07-06 07:31 UTC, gerseystelmach submitted a review, later dismissed

2021-07-06 10:19 UTC, sblondeau requested changes
le contenu du dossier uploads est versionné là ! il ne devrait pas

2021-07-06 13:27 UTC, gerseystelmach approved these changes

2021-07-06 13:41 UTC, merged