S05 us24 affichage des commandes
WildCodeSchool/orleans-202103-php-project-treebz pull request #208
Opened 2021-07-02 09:41 UTC by Valentin-int

2021-07-02 09:56 UTC, gerseystelmach submitted a review, later dismissed

2021-07-04 12:26 UTC, sblondeau requested changes
beaucoup de fichiers dans cette PR, dans l'ensemble c'est propre, mais tu aurais pu découper en 1/ j'affiche des commande (entity commande)
2/ j'ajoute le lien entre commande et status (creation de l'entité status)
là c'est trop tard, mais ça aurait éviter d'avoir à tout faire (fixtures, make:entity) pour tout d'un coup et on aurait eu 2 PR plus petites

2021-07-04 12:26 UTC, sblondeau commented on src/DataFixtures/CommandFixtures.php
> +            'lastname' => 'Stelmach',
tu ferais mieux d'utiliser faker, tu pourrai générer plus simplement plus de commandes

2021-07-04 12:26 UTC, sblondeau commented on src/DataFixtures/StatusFixtures.php
> +    public const STATUS = ['En cours', 'Livré', 'Annuler'];
Annulé

2021-07-04 12:26 UTC, sblondeau commented on src/Controller/Admin/CommandController.php
> +            'status' => $statusRepository->findAll()
c'est pas inutile d'envoyer stauts ici vu que tu peux faire command->getStatus() ?

2021-07-04 14:07 UTC, Valentin-int commented on src/Controller/Admin/CommandController.php
> +            'status' => $statusRepository->findAll()
J'utilise le getStatus pour afficher le status en cour mais j'en est besoin pour boucler sur tout les status et pouvoir les afficher dans le select

2021-07-04 14:26 UTC, ChristianOlmedo approved these changes

2021-07-05 07:17 UTC, sblondeau approved these changes

2021-07-05 07:17 UTC, merged