S05 us20 01 previsualisation customers
WildCodeSchool/orleans-202103-php-project-treebz pull request #216
Opened 2021-07-02 12:41 UTC by ChristianOlmedo

2021-07-02 13:07 UTC, Valentin-int submitted a review, later dismissed

2021-07-04 12:29 UTC, sblondeau commented on src/Controller/PreviewController.php
> +        $memberNumber = '10000';
elles servent à quoi ces valuers à 1 ou 1000?

2021-07-04 21:43 UTC, Vannou28 commented on src/Controller/PreviewController.php
> +        $memberNumber = '10000';
c'est pour afficher ou pas une option en fonction de ce que l'on veut (une carte, une faille ou l'ensemble)
ok les 10000 c'est un peu excessif mais c 'est fait pour dire je veux tout et 1 c'est pour avoir qu'un seul paramètre.

2021-07-04 21:45 UTC, Vannou28 commented on src/Controller/PreviewController.php
> +        $memberNumber = '10000';
les paramètres sont utilisé dans les boucles avec l'utilisation des limitation avec slice

2021-07-05 07:16 UTC, sblondeau requested changes

2021-07-05 07:16 UTC, sblondeau commented on src/Controller/PreviewController.php
> +        $memberNumber = '10000';
dsl mais je ne comprends tjs pas l'intéret ? pourquoi un slice ? tu ne veux pas afficher tous tes membres? 
éclaircissez moi ça, mais dans tous les cas c'est sûr et certain qu'on ne pas pas laisser des valeurs arbitraires comme ça (si on devait ça serait des constantes, et pas des int écrits comme des strings)

2021-07-06 08:23 UTC, gerseystelmach approved these changes

2021-07-06 10:23 UTC, sblondeau requested changes

2021-07-06 10:23 UTC, sblondeau commented on src/Controller/CardController.php
>       * @ParamConverter("command", class="App\Entity\Command", options={"mapping": {"command_id": "id"}})
pourquoi un @paramconverter ici ? 
juste un /carte/{id} suffit

2021-07-06 10:23 UTC, sblondeau commented on src/Controller/PreviewController.php
> +     * @ParamConverter("command", class="App\Entity\Command", options={"mapping": {"command_id": "id"}})
idem

2021-07-06 10:23 UTC, sblondeau commented on templates/base.html.twig
> +        {% block preview %}{% endblock %}
pb d'indentation là ?

2021-07-06 10:23 UTC, sblondeau commented on templates/base.html.twig
> +        {% block preview %}{% endblock %}
et je ne vois pas trop l'intéret du block preview

2021-07-06 10:23 UTC, sblondeau commented on templates/gameCreation/preview.html.twig
> +                        {% block preview %}
pourquoi un bloc ? tu peux te contenter de ton include là non ? (ou j'ai zappé qq chose)

2021-07-06 10:23 UTC, sblondeau commented on templates/gameCreation/theme.html.twig
> +                                <a href="{{ path('gamecreation_preview', {'command_id': command.id}) }}" class="btn btn-primary text-uppercase fw-bold fw-bold fs-5 w-100 mt-5">Passer la commande
attention si tu enlèves le @paramconverter ici ca devient {{ path('gamecreation_preview', {'id': command.id}) }}"

2021-07-06 14:58 UTC, Vannou28 approved these changes

2021-07-06 15:26 UTC, sblondeau approved these changes

2021-07-06 15:26 UTC, merged