US26 - User managemenet for the admin part
WildCodeSchool/orleans-202103-php-project-treebz pull request #218
Opened 2021-07-02 15:23 UTC by gerseystelmach

2021-07-02 21:19 UTC, ChristianOlmedo approved these changes

2021-07-04 12:32 UTC, sblondeau requested changes

2021-07-04 12:32 UTC, sblondeau commented on templates/admin/user/index.html.twig
> +    {# <a href="{{ path('admin_user_new') }}">Create new</a></main> #}
code commenté à enlever

2021-07-04 12:32 UTC, sblondeau commented on templates/admin/user/index.html.twig
> +        {% for user_detail in user_details|sort((a, b) => a.lastname <=> b.lastname) %}
fait plutot le tri en remplaçant le findAll par un findBy() dans le controller, c'est plus logique (car on souhaite tjs avoir ces données par ordre alphabétique) et je pense plus performant aussi, que de gérer ça dans la vue.

2021-07-05 09:42 UTC, Valentin-int approved these changes

2021-07-05 10:16 UTC, sblondeau requested changes

2021-07-05 10:16 UTC, sblondeau commented on templates/admin/user/index.html.twig
> +                                {{ user_detail.id }}</p>
est-ce intéressant d'afficher l'id du client ? je ne pense pas

2021-07-05 10:16 UTC, sblondeau commented on templates/admin/user/index.html.twig
> +                            <span>{{ user_detail.id }}</span>
idem

2021-07-05 10:16 UTC, sblondeau commented on templates/admin/user/index.html.twig
> +                    <div class="col-12 col-md-2 mt-3 py-3 py-md-1 text-center">
pas de col-12, c'est inutile car déjà col-12 par défaut

2021-07-05 10:29 UTC, Valentin-int approved these changes

2021-07-06 10:24 UTC, sblondeau approved these changes

2021-07-06 10:24 UTC, merged