creation d'un servive pour le prix d un jeu
WildCodeSchool/orleans-202103-php-project-treebz pull request #219
Opened 2021-07-04 21:34 UTC by Vannou28

2021-07-05 09:40 UTC, gerseystelmach submitted a review, later dismissed

2021-07-05 10:30 UTC, sblondeau requested changes

2021-07-05 10:30 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $priceGameCard = new PriceGameCard();
NON ! tu dois injecter le service en paramètre de ta méthode de service, et justement ne pas l'instancier ici

2021-07-05 10:30 UTC, sblondeau commented on src/Service/PriceGameCard.php
> +            $price = " trop de membres";
non ici ça devrait plutot de revoyer une exception

2021-07-05 10:30 UTC, sblondeau commented on src/Service/PriceGameCard.php
> +    public function priceGame(int $nbCars): ?string
la méthode devrait revoyer un float.
Le "€" est à ajouter à l'affichage coté Twig. Comme ça tu peux réutiliser la méthode à d'autre moment (sur ton total final, quand tu ajoutes d'autres frais par ex)

2021-07-05 10:30 UTC, sblondeau commented on src/Service/PriceGameCard.php
> +    public function priceGame(int $nbCars): ?string
int $cards ? et non nbCar ?
mais en réalité, tu pourrais tout aussi bien passer un objet Command je pense

2021-07-05 10:30 UTC, sblondeau commented on templates/gameCreation/index.html.twig
> +                        <span class="fw-bold ms-3 price">24.99 €</span>
réutilise les valeurs de tes constantes dans le Twig (via constant() ) regarde la doc de Twig

2021-07-05 10:30 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $priceGame = $priceGameCard->priceGame(count($command->getMembers()));
passe plutot un objet Command. 
le count() sur $command->getMembers()  peut renvoyer une erreur s'il n'y a pas de membres
il faudra ajouter un try/catch pour attraper d'eventuelles exception (voir plus bas)

2021-07-05 10:30 UTC, sblondeau commented
En bonus, un petit test unitaire ne serait pas très compliqué à faire et ça serait intéressant ;-)

2021-07-06 10:08 UTC, ChristianOlmedo submitted a review, later dismissed

2021-07-06 10:27 UTC, sblondeau requested changes

2021-07-06 10:27 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $priceGame = $priceGameCard->priceGame(count($command->getMembers()));
non modifié

2021-07-06 10:27 UTC, sblondeau requested changes

2021-07-06 10:27 UTC, sblondeau commented on src/Service/PriceGameCard.php
> +    public function priceGame(int $cars): ?float
cars ? cards plutot ? mais voire mon autre commentaire plus haut sinon

2021-07-06 13:26 UTC, gerseystelmach approved these changes

2021-07-06 15:27 UTC, sblondeau commented on src/Controller/MemberController.php
> +        $priceGame = $priceGameCard->priceGame(count($command->getMembers()));
je repasse en change requested le temps que tu push tes dernières modifs

2021-07-07 07:32 UTC, ChristianOlmedo approved these changes

2021-07-07 07:59 UTC, sblondeau approved these changes

2021-07-07 07:59 UTC, merged