Game rules page complete
WildCodeSchool/orleans-202103-php-project-treebz pull request #22
Opened 2021-06-03 13:06 UTC by gerseystelmach

2021-06-03 13:50 UTC, ChristianOlmedo approved these changes

2021-06-03 14:40 UTC, ChristianOlmedo approved these changes

2021-06-03 14:40 UTC, Valentin-int approved these changes

2021-06-03 17:25 UTC, sblondeau requested changes

2021-06-03 17:25 UTC, sblondeau commented on assets/images/Vector(1).svg
> +<svg width="1300" height="37" viewBox="0 0 420 37" fill="none" xmlns="http://www.w3.org/2000/svg">
revoir le nom du fichier qui a des parenthèses

2021-06-03 17:25 UTC, sblondeau commented on assets/images/Vector(1).svg
> +<svg width="1300" height="37" viewBox="0 0 420 37" fill="none" xmlns="http://www.w3.org/2000/svg">
et y a aussi un Vector.svg, un doublon ?

2021-06-03 17:25 UTC, sblondeau commented on assets/styles/gamerules.scss
> +.btn-blue {
pourquoi ne pas passer la couleur $secondary en blue et utiliser tout simplement un btn-secondary de bootstrap ?

2021-06-03 17:25 UTC, sblondeau commented on assets/styles/gamerules.scss
> +h1 {
le code de ton h1 est quasi le meme que celui du h2 défini dans app.scss
il faut mutualiser les choses là.

2021-06-03 17:25 UTC, sblondeau commented on assets/styles/variables.scss
> +cursive;
pourquoi 2 lignes ?

2021-06-03 17:25 UTC, sblondeau commented on src/Controller/RulesController.php
> +class RulesController extends AbstractController
Rule au SINGULIER !! il faut tout renommer

2021-06-03 17:25 UTC, sblondeau commented on templates/gamerules/index.html.twig
> +{% block navbar %}
si tu redefinis un block navbar vide ou un block title vide, tu n'auras ni title ni navbar.
De plus ta page doit étendre layout et pas base

2021-06-04 07:27 UTC, gerseystelmach commented on assets/images/Vector(1).svg
> +<svg width="1300" height="37" viewBox="0 0 420 37" fill="none" xmlns="http://www.w3.org/2000/svg">
J'avais fait un test et j'ai oublié de les supprimer. Deleted!

2021-06-04 07:31 UTC, gerseystelmach commented on assets/styles/gamerules.scss
> +.btn-blue {
Le style.css a fait en utilisant  le $secondary avec la coleur jeune. Je pense que s'on change maintenant ce variable il peut casser les autres US. Comme la client a choisi les buttons en bleu, je vais mettre ce class dans app.scss, comme ça tout le monde peut profiter de la meme class.

2021-06-04 07:43 UTC, gerseystelmach commented on assets/styles/gamerules.scss
> +h1 {
On peut pas mettre le style par default pour tous les h1, car il y a de h1 dans le projet que prends pas le style. Cependant, je vais faire un classe avec ce config, mais j'ai toujours besoin de separer le h1 et h2, car ils prennent differents tailles pour le ::after.

2021-06-04 07:44 UTC, gerseystelmach commented on assets/styles/variables.scss
> +cursive;
Il y a que un ligne avec ce variable.

2021-06-04 07:52 UTC, gerseystelmach commented on src/Controller/RulesController.php
> +class RulesController extends AbstractController
Merci! Corrected!

2021-06-04 08:14 UTC, gerseystelmach commented on templates/gamerules/index.html.twig
> +{% block navbar %}
Corrected!

2021-06-04 08:17 UTC, Valentin-int approved these changes

2021-06-04 09:14 UTC, sblondeau requested changes

2021-06-04 09:14 UTC, sblondeau commented on assets/styles/variables.scss
> +cursive;
non ton font-title est sur 2 lignes ;-)

2021-06-04 09:14 UTC, sblondeau commented on assets/styles/variables.scss
> +cursive;
```
$font-title: 'Lemonada',
cursive;
```

2021-06-04 09:14 UTC, sblondeau commented on src/Controller/RuleController.php
> +        return $this->render('gamerules/index.html.twig');
gamerule et pas gamerules

2021-06-04 13:07 UTC, Valentin-int submitted a review, later dismissed

2021-06-08 07:41 UTC, sblondeau submitted a review, later dismissed

2021-06-09 09:41 UTC, Valentin-int approved these changes

2021-06-09 11:37 UTC, merged