Fix on the connexion page, fix in the admin navbar, fix in the conditions for the greetings (name or email if there's isnt a name)
WildCodeSchool/orleans-202103-php-project-treebz pull request #221
Opened 2021-07-05 08:37 UTC by gerseystelmach

…ion for the greetings with name and email

2021-07-05 09:40 UTC, Valentin-int approved these changes

2021-07-05 10:24 UTC, sblondeau requested changes

2021-07-05 10:24 UTC, sblondeau commented on src/Controller/TermController.php
> +     * @Route("/protection-des-donnees", name="termsDonnes")
termsData plutot

2021-07-05 10:24 UTC, sblondeau commented on templates/component/_navbar.html.twig
> +                        {% if app.user.userDetail.firstname is defined %}
déjà je mettrais plutot "Bonjour" que "Salut" qui fait un peu familier. Ensuite plutot que ce bloc if/else, tu dois pouvoir écrire
```
{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    Bonjour {{ app.user.userDetail.firstname ?? app.user.email }} 
{% endif %}
```

2021-07-06 07:35 UTC, Vannou28 approved these changes

2021-07-06 10:37 UTC, sblondeau approved these changes

2021-07-06 10:38 UTC, merged