ajout template historique des commandes et ajout de la methode dans l…
WildCodeSchool/orleans-202103-php-project-treebz pull request #228
Opened 2021-07-06 10:13 UTC by Valentin-int

…e userDetailController

2021-07-06 10:26 UTC, ChristianOlmedo approved these changes

2021-07-06 15:31 UTC, sblondeau requested changes

2021-07-06 15:31 UTC, sblondeau commented on migrations/Version20210705082258.php
> +<?php
pour rattraper le pb des migrations, j'ai passé celle de christiant et qqunes des tiennes, mais là retire juste ton fichier de migration (vu que ta PR ne modifie pas la BDD il n'a rien à faire là). Si après vous avez tjs des soucis, posez vous un moment, faites un fix une fois pour toute depuis dev et on repart. 
Mais pour celle-ci, je ne veux pas ce fichier qui est inutile

2021-07-07 20:58 UTC, ChristianOlmedo submitted a review, later dismissed

2021-07-08 06:42 UTC, sblondeau requested changes

2021-07-08 06:42 UTC, sblondeau commented on src/Entity/Command.php
> +        return $this->createdAt->format('d/m/Y');
je ne le ferais pas ici. Le format se fait plutot coté vue avec un |date() en Twig
si tu le fais là, tu vas manipuler un string plutot qu'un objet Datetime, ce qui peut etre limitant si tu veux utiliser cette date autrement dans ton code

2021-07-08 06:42 UTC, sblondeau commented on templates/user_detail/commandHistory.html.twig
> +						<strong>{{ command.createdAt }}</strong>
la le {{ command.createdAt|date('d/m/Y') }}

2021-07-08 07:51 UTC, ChristianOlmedo approved these changes

2021-07-08 08:19 UTC, sblondeau approved these changes

2021-07-08 08:20 UTC, merged