S05 us31 modification des status
WildCodeSchool/orleans-202103-php-project-treebz pull request #241
Opened 2021-07-07 19:31 UTC by Valentin-int

2021-07-07 20:57 UTC, ChristianOlmedo approved these changes

2021-07-08 06:49 UTC, sblondeau requested changes

2021-07-08 06:49 UTC, sblondeau commented on templates/admin/command/index.html.twig
>  						<strong>00.00€</strong>
c'est pas le prix total que tu dois afficher ici ? pas 0.00 en tout cas ?

2021-07-08 08:24 UTC, Valentin-int commented on templates/admin/command/index.html.twig
>  						<strong>00.00€</strong>
Si mais on a pas encore le prix dans notre entity, on le fera passer dans un fix

2021-07-08 08:24 UTC, ChristianOlmedo approved these changes

2021-07-08 09:04 UTC, sblondeau requested changes

2021-07-08 09:04 UTC, sblondeau commented on assets/styles/admin/command.scss
> +.Livré-color {
hum j'avais pas vu ça, c'est moche ! si tu changes la donnée en BDD ça ne fonctionne plus
il faudrait que tu gères ça différment, avec par ex un champ color dans ta table status

2021-07-08 09:39 UTC, Valentin-int commented on templates/admin/command/index.html.twig
>  						<strong>00.00€</strong>
Ok, ca marche, non on à pas encore de {{ command.price }}

2021-07-08 13:43 UTC, ChristianOlmedo approved these changes

2021-07-08 14:30 UTC, sblondeau approved these changes

2021-07-08 14:30 UTC, merged