Us2 navbar boostrap (html+css)
WildCodeSchool/orleans-202103-php-project-treebz pull request #28
Opened 2021-06-03 19:28 UTC by Vannou28

2021-06-04 07:44 UTC, Valentin-int submitted a review, later dismissed

2021-06-04 08:09 UTC, sblondeau requested changes

2021-06-04 08:09 UTC, sblondeau commented on assets/styles/navbar.scss
> +@import 'app.scss';
non tu ne dois pas iimporter app.scss dans navbar puisque tu as créer un fichier navbar.scss que tu appelles justement indépendament de app.scss. Là en faisant ça tu charges donc 2 fois app.scss

2021-06-04 08:09 UTC, sblondeau commented on assets/styles/navbar.scss
> +@media screen and (max-width: 1600px) {
tu le sens que ca fait un peu bricolage tous ces media-queries non ? 
1. tu peux très certainement les éviter.
2. dans tous les cas, il faudrait utiliser les meme brreakpoint que ceux de boostrap 
un exemple pour rendre des polices "fluides" sans media queries (si c'est pertinent dans ton cas)  https://css-tricks.com/snippets/css/fluid-typography/

2021-06-04 13:10 UTC, gerseystelmach approved these changes

2021-06-07 09:42 UTC, ChristianOlmedo approved these changes

2021-06-07 11:47 UTC, sblondeau requested changes

2021-06-07 11:47 UTC, sblondeau commented on templates/base.html.twig
> +
attention à ne pas modifier des fichiers pour rien car ils sont envoyés dans la PR alors qu'ils n'ont pas de rapport avec la US ;-)

2021-06-07 11:47 UTC, sblondeau commented on templates/component/_navbar.html.twig
> +                        <a class="nav-link active" href="#">ACCUEIL</a>
pas de lien accueil

2021-06-07 11:47 UTC, sblondeau commented on templates/component/_navbar.html.twig
> +                        <a class="nav-link active" href="#">CR&#201EZ UN JEU</a>
euh ? tu veux un É en fait  ?

2021-06-07 11:47 UTC, sblondeau commented on assets/styles/navbar.scss
> +@function strip-unit($value) {
dans la doc https://css-tricks.com/snippets/css/fluid-typography/
il faut faire 
font-size: calc([minimum size] + ([maximum size] - [minimum size]) * ((100vw - [minimum viewport width]) / ([maximum viewport width] - [minimum viewport width])));

justement l'exemple de la mixin c'est ce que tu étais obligé de faire AVANT que la fonction calc() native de CSS existe.

2021-06-08 08:53 UTC, Vannou28 commented on templates/component/_navbar.html.twig
> +                        <a class="nav-link active" href="#">ACCUEIL</a>
je l'ai remis pour les vieux

2021-06-08 13:09 UTC, ChristianOlmedo approved these changes

2021-06-09 07:33 UTC, sblondeau approved these changes

2021-06-09 07:33 UTC, merged