changement de numeros des cartes
WildCodeSchool/orleans-202103-php-project-treebz pull request #280
Opened 2021-07-12 09:23 UTC by Vannou28

2021-07-12 10:14 UTC, Valentin-int approved these changes

2021-07-12 10:38 UTC, sblondeau requested changes

2021-07-12 10:38 UTC, sblondeau commented on templates/member/index.html.twig
> +                                        <a href="{{ path('member_up_cardnumber', {'command': command.id, 'member': member.id}) }}"><span class="iconify" data-icon="akar-icons:arrow-down-thick" data-i
ça modifie ta BDD donc je veux des form et pas des links
faire attention à ne pas mettre le lien up pour le 1er et pas le down pour le dernier

2021-07-12 10:38 UTC, sblondeau commented on src/Controller/MemberController.php
> +    public function upCardNumber(
ton code de up et down est le meme à plus ou moins une addition/soustraction => refactorise en une méthode

2021-07-12 10:38 UTC, sblondeau commented on src/Controller/MemberController.php
> +            $memberDown = new Member();
non tu n'as pas à créer un new member ici ? on en reparle tout à l'heure

2021-07-13 07:45 UTC, gerseystelmach submitted a review, later dismissed

2021-07-13 08:39 UTC, sblondeau submitted a review, later dismissed

2021-07-13 08:42 UTC, Valentin-int approved these changes

2021-07-13 08:48 UTC, sblondeau approved these changes

2021-07-13 08:48 UTC, merged