S05 us33 récuperer sa dernière creation
WildCodeSchool/orleans-202103-php-project-treebz pull request #281
Opened 2021-07-12 09:24 UTC by Valentin-int

2021-07-12 09:48 UTC, Vannou28 submitted a review, later dismissed

2021-07-12 10:08 UTC, Vannou28 approved these changes

2021-07-12 10:08 UTC, Vannou28 submitted a review, later dismissed

2021-07-12 12:51 UTC, sblondeau requested changes

2021-07-12 12:51 UTC, sblondeau commented on src/Controller/GameCreationController.php
> +    public function pendingLastOrder(Command $command, CommandRepository $commandRepository): Response
je ne comprends pas à quoi te sert cette méthode, vu que tu envoies la lastCommand à ta vue depuis ta méthode index

2021-07-12 14:28 UTC, gerseystelmach approved these changes

2021-07-12 20:56 UTC, sblondeau requested changes

2021-07-12 20:56 UTC, sblondeau commented on templates/gameCreation/index.html.twig
> +						<a class="text-secondary text-decoration-none" href="{{ path('pending_order', {'id': lastCommand.id}) }}">
ma remarque était que là, tu rediriges vers une méthode pendingOrder qui ne fait elle-meme que rediriger vers member_index.
Pourquoi dans ce cas ne pas mettre direct ici 
```
<a class="text-secondary text-decoration-none" href="{{ path('member_index', {'command': lastCommand.id}) }}">
```
??

2021-07-13 08:00 UTC, gerseystelmach approved these changes

2021-07-13 08:43 UTC, sblondeau requested changes
tu as un fichier pop_up.js qui est vide

2021-07-13 09:08 UTC, gerseystelmach approved these changes

2021-07-13 09:10 UTC, merged