US02 - Ajouter une adresse de livraison
WildCodeSchool/orleans-202103-php-project-treebz pull request #284
Opened 2021-07-12 14:07 UTC by gerseystelmach

2021-07-12 21:01 UTC, Valentin-int approved these changes

2021-07-12 21:29 UTC, sblondeau requested changes

2021-07-12 21:29 UTC, sblondeau commented on migrations/Version20210712094649.php
> +final class Version20210712094649 extends AbstractMigration
ton fichier de migration ne va pas, il ne devrait pas écraser l'ancien mais venir en plus.
supprime ce fichier et récupère celui sur dev
drop ta base
relance un d:m:m
relance les fixtures
puis un make:migration qui va te générer un nouveau fichier avec uniquement les migrations pour ton US

2021-07-12 21:29 UTC, sblondeau commented on src/Entity/ShippingAddress.php
> +     * @ORM\Column(type="string", length=25)
il manque tous les asserts (lenght, notblank...) dans le fichier

2021-07-12 21:29 UTC, sblondeau commented on src/Entity/ShippingAddress.php
> +    public function getFullAddresses(): ?string
getFullAdress() plutot (au singulier)

2021-07-12 21:29 UTC, sblondeau commented on src/Form/SelectAddressType.php
> +                'choice_label' => function (ShippingAddress $fullAddresses) {
normalement `'choice_label' => 'fullAddress'` doit fonctionner

2021-07-13 07:43 UTC, gerseystelmach commented on src/Form/SelectAddressType.php
> +                'choice_label' => function (ShippingAddress $fullAddresses) {
Porquoi ça marche?? J'ai pas compris oú il prend l'association de fullAddress et le getter.

2021-07-13 07:45 UTC, Valentin-int approved these changes

2021-07-13 08:44 UTC, sblondeau approved these changes

2021-07-13 08:44 UTC, merged