changement statuts de commande apres avoir paye
WildCodeSchool/orleans-202103-php-project-treebz pull request #331
Opened 2021-07-15 15:44 UTC by Vannou28

2021-07-15 16:36 UTC, ChristianOlmedo approved these changes

2021-07-15 20:40 UTC, sblondeau requested changes

2021-07-15 20:40 UTC, sblondeau commented on src/Controller/ThanksController.php
> +        $status = $statusRepository->findOneByName(['name' => 'Commandée']);
1. vous n'avez pas une constante pour le 'Commandée' ? si non en faire une ça sera plus propre que de mettre cette string en dur
2. si je fais /thanks/22 et que la commande 22 est pas à moi ?

2021-07-16 08:05 UTC, ChristianOlmedo approved these changes

2021-07-16 08:42 UTC, sblondeau approved these changes

2021-07-16 08:42 UTC, merged