fix chargement commande en cours dans la creation de jeu
WildCodeSchool/orleans-202103-php-project-treebz pull request #332
Opened 2021-07-15 16:00 UTC by Vannou28

2021-07-15 16:37 UTC, ChristianOlmedo approved these changes

2021-07-15 20:41 UTC, sblondeau requested changes

2021-07-15 20:41 UTC, sblondeau commented on src/Controller/GameCreationController.php
> +        $lastCommand = $commandRepository->findOneBy(['user' => $user, 'status' => '1'], ['createdAt' => 'desc']);
c'est quoi le status "1" ? là encore, faire une constante peut-etre ?

2021-07-16 08:05 UTC, ChristianOlmedo approved these changes

2021-07-16 08:42 UTC, sblondeau approved these changes

2021-07-16 08:42 UTC, merged