Fix buttons page crop
WildCodeSchool/orleans-202103-php-project-treebz pull request #360
Opened 2021-07-20 14:59 UTC by gerseystelmach

2021-07-21 06:47 UTC, ChristianOlmedo submitted a review, later dismissed

2021-07-21 06:59 UTC, sblondeau requested changes

2021-07-21 06:59 UTC, sblondeau commented on templates/member/crop.html.twig
> +            </br>
pas de br en dehors d'un p !  vu ta page, le mieux ici est je pense de mettre un nouveau p sous le 1er

2021-07-23 10:06 UTC, Valentin-int approved these changes

2021-07-23 13:39 UTC, sblondeau approved these changes

2021-07-23 13:39 UTC, merged