Us5 06 navbar admin
WildCodeSchool/orleans-202103-php-project-treebz pull request #44
Opened 2021-06-04 17:46 UTC by Vannou28

2021-06-07 08:57 UTC, ChristianOlmedo approved these changes

2021-06-07 11:56 UTC, sblondeau requested changes

2021-06-07 11:56 UTC, sblondeau commented on assets/styles/navbar_admin.scss
> +$width-logo: 200px;
meme pb que pour l'autre US.
Dans tous les cas, tu devrais pas avoir à répéter ce code. Il faut réutiliser le css de navbar.css au maximum, et dans un navbar_admin tu mets le css qui est différenciant uniquement.

2021-06-07 11:56 UTC, sblondeau commented on templates/component/_navbar_admin.html.twig
> +                        <a class="nav-link active" href="#">ACCUEIL admin</a>
ici par contre tu peux garder accueil admin si ton logo te renvoie tjs vers la page d'accueil coté visiteur.

2021-06-08 13:23 UTC, ChristianOlmedo approved these changes

2021-06-09 07:34 UTC, sblondeau approved these changes

2021-06-09 07:34 UTC, merged