S02 us01 page accueil admin
WildCodeSchool/orleans-202103-php-project-treebz pull request #47
Opened 2021-06-08 07:37 UTC by Valentin-int

2021-06-08 07:39 UTC, ChristianOlmedo approved these changes

2021-06-08 11:32 UTC, sblondeau commented on templates/admin/index.html.twig
> +    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
alors tu utilises iconify. En soit pas de soucis pour utiliser une lib d'icones, mais il faut que vous vous mettiez d'accord pour que vous utilisiez bien tous la même. Dans ce cas, y a de très forte chance que vous trouviez des icones sur toutes les pages et tu pourrais charger la lib direct depuis base.html.twig.

2021-06-09 07:40 UTC, sblondeau requested changes

2021-06-09 07:40 UTC, sblondeau commented on templates/admin/index.html.twig
> +    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
et vu qu'on utilise webpack, l'idée c'est de ne pas utiliser un CDN en direct ici.
Fais plutot ce qu'il y a expliqué ici  https://docs.iconify.design/implementations/svg-framework/#usage
donc en gros 
```
 yarn add @iconify/iconify
```
et ajoute dans app.js une ligne `import Iconify from '@iconify/iconify';`

un coup de yarn encore dev et c'est bon

2021-06-09 07:40 UTC, sblondeau commented on templates/admin/index.html.twig
> +    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
et donc plus besoin de charger le script

2021-06-09 08:22 UTC, ChristianOlmedo approved these changes

2021-06-09 08:44 UTC, sblondeau approved these changes

2021-06-09 08:44 UTC, merged