S02 us03 page creation de theme
WildCodeSchool/orleans-202103-php-project-treebz pull request #51
Opened 2021-06-08 16:34 UTC by Valentin-int

2021-06-08 20:38 UTC, Vannou28 approved these changes

2021-06-09 07:48 UTC, sblondeau requested changes

2021-06-09 07:48 UTC, sblondeau commented on src/Entity/Theme.php
> +     * @Assert\Length(max="255", maxMessage="Le champ saisie ne peut dépasser {{ limit }} caractères")
pas besoin de traduire les message, met juste "fr" dans le fichier config>packages>translation.yaml

2021-06-09 07:48 UTC, sblondeau commented on src/Entity/Theme.php
> +     * @Assert\Length(max="255", maxMessage="Le champ saisie ne peut dépasser {{ limit }} caractères")
ajoute un assert pour vérifier que tu as bin un format de couleur. #XXXXXX
tu peux faire ça via https://symfony.com/doc/current/reference/constraints/Regex.html

et ta longueur sera tjs 7 caractères non ? donc modif ta bdd pour une length de 7

2021-06-09 07:48 UTC, sblondeau commented on src/Form/ThemeType.php
> +            ->add('styleText', TextType::class, ['label' => 'Style du texte']);
comment ça sera gérer ? un choix libre ? un choix dans une liste de polices ? si c'est un choix libre comment gérer le chargmeent de la police ? Si c'est un choix dans une liste, il faut une relation avec une autre table (et je ferai ça dans une autre US)

2021-06-09 09:46 UTC, Vannou28 submitted a review, later dismissed

2021-06-09 13:27 UTC, sblondeau requested changes

2021-06-10 08:50 UTC, ChristianOlmedo submitted a review, later dismissed

2021-06-10 09:48 UTC, sblondeau requested changes

2021-06-10 09:48 UTC, sblondeau commented on src/Entity/Theme.php
> +     * @Assert\Regex("/(?:#|0x)(?:[a-f0-9]{3}|[a-f0-9]{6})\b|(?:rgb|hsl)a?\([^\)]*\)/")
l'idée c'est que tu modifie ta Regex par celle que je t'ai donné. La tienne ne fonctionne pas car elle prend en compte tous les types de couleurs, alors qu'on aura que des couleurs hexadecimales là

2021-06-10 10:08 UTC, Valentin-int commented
Oui effectivement, je pensais l'avoir changé

2021-06-10 10:11 UTC, Vannou28 approved these changes

2021-06-10 12:19 UTC, sblondeau approved these changes

2021-06-10 12:19 UTC, merged